# Generated by Django 6.0 on 2025-12-24 14:11

import apps.visualization.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('ml_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlotArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_type', models.CharField(choices=[('DATASET_DISTRIBUTION', 'Dataset Distribution'), ('CORRELATION_MATRIX', 'Correlation Matrix'), ('DECISION_BOUNDARY', 'Decision Boundary'), ('LEARNING_CURVE', 'Learning Curve'), ('MODEL_COMPARISON', 'Model Comparison')], db_index=True, max_length=24)),
                ('title', models.CharField(max_length=180)),
                ('image_file', models.FileField(blank=True, upload_to=apps.visualization.models.plot_upload_path)),
                ('plotly_json', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict, help_text='How the plot was generated (columns, params).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='datasets.datasetversion')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='ml_models.experiment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='datasets.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'project', 'plot_type', 'created_at'], name='visualizati_owner_i_35067e_idx')],
            },
        ),
    ]
