# Generated by Django 6.0 on 2025-12-24 14:11

import apps.ml_models.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable identifier (e.g., 'logistic-regression', 'random-forest').", max_length=60, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('family', models.CharField(choices=[('REGRESSION', 'Regression'), ('CLASSIFICATION', 'Classification'), ('CLUSTERING', 'Clustering'), ('NEURAL_NETWORK', 'Neural Network')], db_index=True, max_length=20)),
                ('sklearn_class_path', models.CharField(blank=True, max_length=200)),
                ('supported_tasks', models.JSONField(default=list, help_text="List like ['CLASSIFICATION'] or ['REGRESSION','CLASSIFICATION'] depending on algorithm usage.")),
                ('default_hyperparameters', models.JSONField(default=dict)),
                ('hyperparameter_schema', models.JSONField(default=dict, help_text='JSON schema to drive dynamic forms: field types, ranges, enums, help text.')),
                ('educational_summary', models.TextField(help_text='Short student-friendly summary of how it works.')),
                ('educational_details_md', models.TextField(help_text='Longer explanation in Markdown (math intuition + steps).')),
                ('prerequisites_md', models.TextField(blank=True, help_text='Background knowledge (e.g., vectors, probability, gradients). Markdown.')),
                ('typical_use_cases_md', models.TextField(blank=True, help_text='When to use / when not to use. Markdown.')),
                ('strengths_md', models.TextField(blank=True)),
                ('limitations_md', models.TextField(blank=True)),
                ('references', models.JSONField(default=list, help_text='List of references: [{title, author, year, link}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['family', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('test_size', models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('use_cross_validation', models.BooleanField(default=True)),
                ('cv_folds', models.PositiveIntegerField(default=5)),
                ('random_seed', models.PositiveIntegerField(default=42)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], default='PENDING', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('run_logs', models.TextField(blank=True)),
                ('runtime_meta', models.JSONField(default=dict, help_text='Versions: python, sklearn, pandas; dataset hash; etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiments', to='ml_models.algorithm')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='datasets.datasetversion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='datasets.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrics', models.JSONField(default=dict)),
                ('confusion_matrix', models.JSONField(blank=True, default=dict)),
                ('curves', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='ml_models.experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('task_type', models.CharField(choices=[('REGRESSION', 'Regression'), ('CLASSIFICATION', 'Classification'), ('CLUSTERING', 'Clustering')], db_index=True, max_length=20)),
                ('target_column', models.CharField(blank=True, help_text='Required for supervised tasks.', max_length=140)),
                ('feature_columns', models.JSONField(default=list, help_text="List of selected feature column names; empty means 'all except target'.")),
                ('random_seed', models.PositiveIntegerField(default=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='datasets.datasetversion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='datasets.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_name', models.CharField(max_length=140)),
                ('expression', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_features', to='ml_models.pipeline')),
            ],
        ),
        migrations.AddField(
            model_name='experiment',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='ml_models.pipeline'),
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('MISSING_VALUES', 'Missing Values'), ('ENCODING', 'Encoding'), ('SCALING', 'Scaling'), ('FEATURE_SELECTION', 'Feature Selection'), ('POLYNOMIAL_FEATURES', 'Polynomial Features'), ('MANUAL_FEATURES', 'Manual Features')], db_index=True, max_length=24)),
                ('order', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(default=dict, help_text="Step configuration (e.g., strategy='mean', scaler='standard', encoder='onehot').")),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ml_models.pipeline')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PredictionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_meta', models.JSONField(default=dict, help_text='Info about input rows/source used for prediction.')),
                ('output_file', models.FileField(upload_to=apps.ml_models.models.prediction_upload_path)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='ml_models.experiment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlgorithmTutorialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content_md', models.TextField(help_text='Markdown tutorial content.')),
                ('quiz_questions', models.JSONField(blank=True, default=list, help_text='Optional: list of quiz questions for students (MCQ/short).')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_sections', to='ml_models.algorithm')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['algorithm', 'order'], name='ml_models_a_algorit_1dc9f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='CVFoldResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fold_index', models.PositiveIntegerField()),
                ('metrics', models.JSONField(default=dict)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_fold_results', to='ml_models.experiment')),
            ],
            options={
                'ordering': ['fold_index'],
                'constraints': [models.UniqueConstraint(fields=('experiment', 'fold_index'), name='uniq_fold_per_experiment')],
            },
        ),
        migrations.CreateModel(
            name='ExportArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('MODEL_PKL', 'Model (.pkl)'), ('REPORT_PDF', 'Evaluation Report (PDF)'), ('REPORT_CSV', 'Evaluation Report (CSV)'), ('PLOT_PNG', 'Visualization (PNG)'), ('PREDICTIONS_CSV', 'Predictions (CSV)'), ('BUNDLE_ZIP', 'Bundle (ZIP)')], db_index=True, max_length=20)),
                ('file', models.FileField(upload_to=apps.ml_models.models.export_upload_path)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to='ml_models.experiment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='datasets.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'project', 'export_type', 'created_at'], name='ml_models_e_owner_i_a23ead_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.ml_models.models.model_artifact_upload_path)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('feature_names', models.JSONField(default=list)),
                ('target_name', models.CharField(blank=True, max_length=140)),
                ('class_labels', models.JSONField(blank=True, default=list)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_artifact', to='ml_models.experiment')),
            ],
            options={
                'indexes': [models.Index(fields=['sha256'], name='ml_models_m_sha256_091ff4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pipeline',
            index=models.Index(fields=['owner', 'project', 'dataset_version'], name='ml_models_p_owner_i_80a7d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipeline',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_pipeline_name_per_project'),
        ),
        migrations.AddConstraint(
            model_name='manualfeature',
            constraint=models.UniqueConstraint(fields=('pipeline', 'output_name'), name='uniq_manual_feature_name_per_pipeline'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['owner', 'project', 'status', 'created_at'], name='ml_models_e_owner_i_aefe20_idx'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['algorithm', 'created_at'], name='ml_models_e_algorit_1bc1a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='experiment',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='uniq_experiment_name_per_project'),
        ),
        migrations.AddIndex(
            model_name='pipelinestep',
            index=models.Index(fields=['pipeline', 'order'], name='ml_models_p_pipelin_3e3f4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestep',
            constraint=models.UniqueConstraint(fields=('pipeline', 'order'), name='uniq_step_order_per_pipeline'),
        ),
    ]
